// DATA LOADING
export const LIST_REQUEST = 'LIST_REQUEST';
export const LIST_UPDATE = 'LIST_UPDATE';
export const LIST_SUCCESS = 'LIST_SUCCESS';
export const LIST_FAILURE = 'LIST_FAILURE';

export const DETAIL_REQUEST = 'DETAIL_REQUEST';
export const DETAIL_UPDATE = 'DETAIL_UPDATE';
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS';
export const DETAIL_FAILURE = 'DETAIL_FAILURE';

// DATALOADER
export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';

// WEB3
export const WEB3_REQUEST = 'WEB3@@/REQUEST'
export const WEB3_SUCCESS = 'WEB3@@/SUCCESS'
export const WEB3_FAILURE = 'WEB3@@/FAILURE'

export const CONTRACT_DEPLOY_REQUEST = 'CONTRACT_DEPLOY@@/REQUEST';
export const CONTRACT_DEPLOY_SUCCESS = 'CONTRACT_DEPLOY@@/SUCCESS';
export const CONTRACT_DEPLOY_FAILURE = 'CONTRACT_DEPLOY@@/FAILURE';